name: Temporary cleanup

on:
  issues:
    types: [opened]

jobs:
  cleanup:
    if: startsWith(github.event.issue.title, '[cleanup]') && github.event.issue.user.login == github.repository_owner
    permissions:
      contents: write
      actions: write
      issues: write
    uses: Uhrendoktor/GPT-ToolsAndStorage/.github/workflows/tool-ref-cleanup.yml@main
    with:
      refs: ''
      cleanup_actions: true
      issue_number: ${{ github.event.issue.number }}
      cleanup_workflow: .github/workflows/_cleanup.yml
    secrets: inherit
