name: Temporary cleanup

on:
  push:
    paths:
      - '.github/workflows/_cleanup.yml'

jobs:
  cleanup:
    permissions:
      contents: write
      actions: write
      issues: write
    uses: Uhrendoktor/GPT-ToolsAndStorage/.github/workflows/tool-ref-cleanup.yml@main
    with:
      refs: ''
      cleanup_actions: true
      issue_number: 2
      cleanup_workflow: .github/workflows/_cleanup.yml
    secrets: inherit
