name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scribus-version: [1.6.5, 1.6.6]

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Scribus
        run: |
          chmod +x ./build-scribus.sh
          SCRIBUS_VERSION=${{ matrix.scribus-version }} ./build-scribus.sh

      - name: Build Plugin
        run: |
          chmod +x ./build-plugin.sh
          SCRIBUS_VERSION=${{ matrix.scribus-version }} VERSION=${{ github.ref_name }} ./build-plugin.sh

      - name: Verify exported artifact
        run: |
          ls -lah ./dist
          test -f ./dist/photobookbrowser-${{ github.ref_name }}-scribus-${{ matrix.scribus-version }}-linux-x86_64.so

      - name: Upload artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/photobookbrowser-${{ github.ref_name }}-scribus-${{ matrix.scribus-version }}-linux-x86_64.so